package org.abc.credit.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-02-19T12:16:09.931-06:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "CreditHistoryServiceService", 
                  wsdlLocation = "file:/home/development/workspace/loanProcessService/src/main/resources/wsdl/CreditHistoryService.wsdl",
                  targetNamespace = "http://service.credit.abc.org/") 
public class CreditHistoryServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.credit.abc.org/", "CreditHistoryServiceService");
    public final static QName CreditHistoryServicePort = new QName("http://service.credit.abc.org/", "creditHistoryServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/development/workspace/loanProcessService/src/main/resources/wsdl/CreditHistoryService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreditHistoryServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/development/workspace/loanProcessService/src/main/resources/wsdl/CreditHistoryService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreditHistoryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreditHistoryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditHistoryServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CreditHistoryService
     */
    @WebEndpoint(name = "creditHistoryServicePort")
    public CreditHistoryService getCreditHistoryServicePort() {
        return super.getPort(CreditHistoryServicePort, CreditHistoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditHistoryService
     */
    @WebEndpoint(name = "creditHistoryServicePort")
    public CreditHistoryService getCreditHistoryServicePort(WebServiceFeature... features) {
        return super.getPort(CreditHistoryServicePort, CreditHistoryService.class, features);
    }

}
