
package org.abc.credit.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-02-19T12:16:09.883-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "CreditHistoryValidationException", targetNamespace = "http://service.credit.abc.org/")
public class CreditHistoryValidationException_Exception extends Exception {
    
    private org.abc.credit.service.CreditHistoryValidationException creditHistoryValidationException;

    public CreditHistoryValidationException_Exception() {
        super();
    }
    
    public CreditHistoryValidationException_Exception(String message) {
        super(message);
    }
    
    public CreditHistoryValidationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CreditHistoryValidationException_Exception(String message, org.abc.credit.service.CreditHistoryValidationException creditHistoryValidationException) {
        super(message);
        this.creditHistoryValidationException = creditHistoryValidationException;
    }

    public CreditHistoryValidationException_Exception(String message, org.abc.credit.service.CreditHistoryValidationException creditHistoryValidationException, Throwable cause) {
        super(message, cause);
        this.creditHistoryValidationException = creditHistoryValidationException;
    }

    public org.abc.credit.service.CreditHistoryValidationException getFaultInfo() {
        return this.creditHistoryValidationException;
    }
}
